[project]
name = "interchange"
version = "0.1.0"
description = ""
authors = [
    {name = "Kikis", email = "kikispcmr@gmail.com"}
]
requires-python = ">=3.12, <3.13"
dependencies = [
    "pytest>=9.0.3",
    "torch>=2.0.0",
    "numpy",
    "boolean.py",
    "transformers>=4.30.0",
    "tqdm",
    "seaborn",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
